### ISSUE TITLE
Failed to Create NoMoreCookies Services, Error Code: 1073

### ISSUE THREAD

**Issue by ryan2551-coder** [AdvDebug/NoMoreCookies#12]

**Comment by AdvDebug** [comment]
that means that the service already exists, you probably didn't uninstall it first after the new update.

**Comment by AdvDebug** [comment]
also you don't have to do that, but it's more recommended to install NoMoreCookies in a SecureBoot-Disabled Environment to get the full protection of it as it doesn't fully support secureboot yet.

**Comment by ryan2551-coder** [comment]
thank for advice my problem is solved 👌

**Comment by AdvDebug** [comment]
no problem, thanks for using the project it really means a lot knowing that people appreciate my work!
