### ISSUE TITLE
Protect more

### ISSUE THREAD

**Issue by furax124** [AdvDebug/NoMoreCookies#13]
Protect against stealer advanced who have admin and kill process of your protect cookies

**Comment by AdvDebug** [comment]
even stealers with admins are still protected against, and for killing processes i don't think this is a good idea, i think it's better to let the user decide.

**Comment by Thibaud1255** [comment]
> even stealers with admins are still protected against, and for killing processes i don't think this is a good idea, i think it's better to let the user decide.

why ? its better if you do a good protection like have autorisation of system just a stealer whos as admin can kill process and stoll information if you cant counter that your cookie protector is bad

**Comment by Thibaud1255** [comment]
you can add fully protected browsers like password stealer ect do a complete protection

**Comment by Thibaud1255** [comment]
> > > even stealers with admins are still protected against, and for killing processes i don't think this is a good idea, i think it's better to let the user decide.
> > 
> > 
> > why ? its better if you do a good protection like have autorisation of system just a stealer whos as admin can kill process and stoll information if you cant counter that your cookie protector is bad
> 
> do you know how the protection even work? are you stupid? there's no "process" that is being created when the protection is enabled in the first place, i don't like being rude but you can't call a project "bad" because there's a feature that the developer don't want to add, i won't kill a process that tried to access browser files, it's better to let the user know and block it.

but how ?

**Comment by Fadi002** [comment]
> > > > even stealers with admins are still protected against, and for killing processes i don't think this is a good idea, i think it's better to let the user decide.
> > > 
> > > 
> > > why ? its better if you do a good protection like have autorisation of system just a stealer whos as admin can kill process and stoll information if you cant counter that your cookie protector is bad
> > 
> > do you know how the protection even work? are you stupid? there's no "process" that is being created when the protection is enabled in the first place, i don't like being rude but you can't call a project "bad" because there's a feature that the developer don't want to add, i won't kill a process that tried to access browser files, it's better to let the user know and block it.
> 
> but how ?

Read the source code and you will figure out how !
