### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by furax124** [AdvDebug/NoMoreCookies#14]
Hello i want to compile src but idk how to found the dll like xnomorecookies or mininomorecookied and when I compile cookie installer folder with sln its do a error can you told how you compile it with picture ? Win+maj+s for screen easy

**Comment by AdvDebug** [comment]
the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.

**Comment by furax124** [comment]
> the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.

Well I send you error after this but can you send me picture how you do this ? Cause I'm not very good to do this I'm am very sry if you can send me picture how you do this and modify main.cpp thank you

**Comment by furax124** [comment]
> the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.

Then what is service like x64 and more ? How can I compile this I know compile service but x64 and no x64 I don't understand this maybe a x86 ?

**Comment by AdvDebug** [comment]
you can find the service source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookiesService).

**Comment by AdvDebug** [comment]
> > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> 
> Well I send you error after this but can you send me picture how you do this ? Cause I'm not very good to do this I'm am very sry if you can send me picture how you do this and modify main.cpp thank you

you can install visual studio and download c++ sdk then you can open the solution and modify it, and the code is really easy to understand and modify so if you don't know how to modify it then it's better to have some knowledge about c/c++ first before modifying such project, and for building it you can google "how to build a c++ dll" and you will know how to build it.

**Comment by furax124** [comment]
> > > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> 
> > 
> 
> > Well I send you error after this but can you send me picture how you do this ? Cause I'm not very good to do this I'm am very sry if you can send me picture how you do this and modify main.cpp thank you
> 
> 
> 
> you can install visual studio and download c++ sdk then you can open the solution and modify it, and the code is really easy to understand and modify so if you don't know how to modify it then it's better to have some knowledge about c/c++ first before modifying such project, and for building it you can google "how to build a c++ dll" and you will know how to build it.

Okay I'm gonna try this thx

**Comment by furax124** [comment]
> > > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> > 
> > 
> > Well I send you error after this but can you send me picture how you do this ? Cause I'm not very good to do this I'm am very sry if you can send me picture how you do this and modify main.cpp thank you
> 
> you can install visual studio and download c++ sdk then you can open the solution and modify it, and the code is really easy to understand and modify so if you don't know how to modify it then it's better to have some knowledge about c/c++ first before modifying such project, and for building it you can google "how to build a c++ dll" and you will know how to build it.

the error of compiling on nomorecookies installer folder is: Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur	CS0234	Le nom de type ou d'espace de noms 'Forms' n'existe pas dans l'espace de noms 'System.Windows' (vous manque-t-il une référence d'assembly ?)	NoMoreCookiesInstaller	C:\Users\User\Desktop\NoMoreCookies-main\NoMoreCookiesInstaller\NoMoreCookiesInstaller\Program.cs	3	N/A

**Comment by AdvDebug** [comment]
> > > > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> > > 
> > > 
> > > Well I send you error after this but can you send me picture how you do this ? Cause I'm not very good to do this I'm am very sry if you can send me picture how you do this and modify main.cpp thank you
> > 
> > 
> > you can install visual studio and download c++ sdk then you can open the solution and modify it, and the code is really easy to understand and modify so if you don't know how to modify it then it's better to have some knowledge about c/c++ first before modifying such project, and for building it you can google "how to build a c++ dll" and you will know how to build it.
> 
> the error of compiling on nomorecookies installer folder is: Gravité Code Description Projet Fichier Ligne État de la suppression Erreur CS0234 Le nom de type ou d'espace de noms 'Forms' n'existe pas dans l'espace de noms 'System.Windows' (vous manque-t-il une référence d'assembly ?) NoMoreCookiesInstaller C:\Users\User\Desktop\NoMoreCookies-main\NoMoreCookiesInstaller\NoMoreCookiesInstaller\Program.cs 3 N/A

just add a reference to "System.Windows.Forms" in the project and you are good to go.

**Comment by furax124** [comment]
> > > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> 
> > 
> 
> > Well I send you error after this but can you send me picture how you do this ? Cause I'm not very good to do this I'm am very sry if you can send me picture how you do this and modify main.cpp thank you
> 
> 
> 
> you can install visual studio and download c++ sdk then you can open the solution and modify it, and the code is really easy to understand and modify so if you don't know how to modify it then it's better to have some knowledge about c/c++ first before modifying such project, and for building it you can google "how to build a c++ dll" and you will know how to build it.

Like idk i need to set true and false ? But how for x and how for mini and how for normale? I am very dumb sry

**Comment by furax124** [comment]
> > > > > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> 
> > > > 
> 
> > > > 
> 
> > > > Well I send you error after this but can you send me picture how you do this ? Cause I'm not very good to do this I'm am very sry if you can send me picture how you do this and modify main.cpp thank you
> 
> > > 
> 
> > > 
> 
> > > you can install visual studio and download c++ sdk then you can open the solution and modify it, and the code is really easy to understand and modify so if you don't know how to modify it then it's better to have some knowledge about c/c++ first before modifying such project, and for building it you can google "how to build a c++ dll" and you will know how to build it.
> 
> > 
> 
> > the error of compiling on nomorecookies installer folder is: Gravité Code Description Projet Fichier Ligne État de la suppression Erreur CS0234 Le nom de type ou d'espace de noms 'Forms' n'existe pas dans l'espace de noms 'System.Windows' (vous manque-t-il une référence d'assembly ?) NoMoreCookiesInstaller C:\Users\User\Desktop\NoMoreCookies-main\NoMoreCookiesInstaller\NoMoreCookiesInstaller\Program.cs 3 N/A
> 
> 
> 
> just add a reference to "System.Windows.Forms" in the project and you are good to go. (and please just use google)

Oh okay sry bro if you can add it for other people it should be good

**Comment by furax124** [comment]
> you can find the service source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookiesService).

I talk about x64 service and no x64 idk 🤷‍♂️

**Comment by furax124** [comment]
> > > > > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> > > > 
> > > > 
> > > > Well I send you error after this but can you send me picture how you do this ? Cause I'm not very good to do this I'm am very sry if you can send me picture how you do this and modify main.cpp thank you
> > > 
> > > 
> > > you can install visual studio and download c++ sdk then you can open the solution and modify it, and the code is really easy to understand and modify so if you don't know how to modify it then it's better to have some knowledge about c/c++ first before modifying such project, and for building it you can google "how to build a c++ dll" and you will know how to build it.
> > 
> > 
> > the error of compiling on nomorecookies installer folder is: Gravité Code Description Projet Fichier Ligne État de la suppression Erreur CS0234 Le nom de type ou d'espace de noms 'Forms' n'existe pas dans l'espace de noms 'System.Windows' (vous manque-t-il une référence d'assembly ?) NoMoreCookiesInstaller C:\Users\User\Desktop\NoMoreCookies-main\NoMoreCookiesInstaller\NoMoreCookiesInstaller\Program.cs 3 N/A
> 
> just add a reference to "System.Windows.Forms" in the project and you are good to go. (and please just use google)

now i have this: Gravité Code Description Projet Fichier Ligne État de la suppression
Erreur CS0103 Le nom 'VersionChecker' n'existe pas dans le contexte actuel NoMoreCookiesInstaller C:\Users\User\Desktop\NoMoreCookies-main\NoMoreCookiesInstaller\NoMoreCookiesInstaller\Program.cs 63 N/A
et Gravité Code Description Projet Fichier Ligne État de la suppression
Avertissement CS0168 La variable 'ex' est déclarée, mais jamais utilisée NoMoreCookiesInstaller C:\Users\User\Desktop\NoMoreCookies-main\NoMoreCookiesInstaller\NoMoreCookiesInstaller\Program.cs 137 N/A
et Gravité Code Description Projet Fichier Ligne État de la suppression
Avertissement CS0168 La variable 'ex' est déclarée, mais jamais utilisée NoMoreCookiesInstaller C:\Users\User\Desktop\NoMoreCookies-main\NoMoreCookiesInstaller\NoMoreCookiesInstaller\Program.cs 212 N/A

**Comment by furax124** [comment]
i already use google and poe.com

**Comment by AdvDebug** [comment]
bro just download the full source from github, you didn't download versionchecker.cs

**Comment by Fadi002** [comment]
> i already use google and poe.com

if you don't know how to do this basic stuff how are you gonna edit the source?

**Comment by furax124** [comment]
> bro just download the full source from github, you didn't download versionchecker.cs

I download it

**Comment by furax124** [comment]
> > i already use google and poe.com
> 
> if you don't know how to do this basic stuff how are you gonna edit the source?

It's just like add path lmao

**Comment by furax124** [comment]
> > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> 
> Then what is service like x64 and more ? How can I compile this I know compile service but x64 and no x64 I don't understand this maybe a x86 ?

I need help about this too

**Comment by AdvDebug** [comment]
> > > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> > 
> > 
> > Then what is service like x64 and more ? How can I compile this I know compile service but x64 and no x64 I don't understand this maybe a x86 ?
> 
> I need help about this too

i don't understand what you are saying here to help you

**Comment by furax124** [comment]
> > > > the dll's like "xnomorecookies" and "mininomorecookies" you can find their source code [here](https://github.com/AdvDebug/NoMoreCookies/tree/main/NoMoreCookies) (you basically just change the mode inside the dllmain.cpp source code and you are good to go) which you can then compile with vs without any problems. and for the "error" you encounter i can't really help you without further information.
> 
> > > 
> 
> > > 
> 
> > > Then what is service like x64 and more ? How can I compile this I know compile service but x64 and no x64 I don't understand this maybe a x86 ?
> 
> > 
> 
> > I need help about this too
> 
> 
> 
> i don't understand what you are saying to help you

Why there two exe of service no more cookies ? What is the x64 and the normale without x64 on the folder of components ?

**Comment by AdvDebug** [comment]
it's exactly what the name suggests, the x64 service injects into x64 processes and x86 into x86 processes, and if the system was x86 it will only install x86 service.

**Comment by furax124** [comment]
> it's exactly what the name suggests, the x64 service injects into x64 processes and x86 into x86 processes, and if the system was x86 it will only install x86 service.

Ok thx 🙏

**Comment by AdvDebug** [comment]
> > it's exactly what the name suggests, the x64 service injects into x64 processes and x86 into x86 processes, and if the system was x86 it will only install x86 service.
> 
> Ok thx 🙏

np
