### ISSUE TITLE
did crash my system

### ISSUE THREAD

**Issue by eikaramba** [AdvDebug/NoMoreCookies#3]
after installation (option1) on windows 10 x64 first i wasn't able to restart anymore. clicking restart was not doing anything and opening task manager was also funky. i just saw little popup windows with the title "checksum" and a checksum within. it was quite randomly happening but the system was definitely behaving quite weird. after a hard reset of the pc, windows wasn't able to boot anymore and i get a blue screen everytime. luckily the system repair was able to fix it and afterwards i was able to boot up the system again.

**Comment by AdvDebug** [comment]
i'm so sorry about that, i forgot to remove the message box code before i release it, this the first and last time that this will happen and i will remove the release until i fix this, as for the next update you won't need SecureBoot disabled to make NoMoreCookies run. thank you for bringing this to my attention before any other thing happens to anybody.

**Comment by AdvDebug** [comment]
i will make sure to analyze the code more carefully and test it more than once to make sure this won't happen again. again, sorry for what happened.

**Comment by AdvDebug** [comment]
the bug have been fixed and [NoMoreCookies](https://github.com/AdvDebug/NoMoreCookies/releases/tag/NoMoreCookies_1.6.1) was tested multiple times, now you can safely install and run the new update of it. i'm sorry again for what happened, i promise nothing like this will ever happen in any feature update.
