### ISSUE TITLE
NoMoreCookies causes Mullvad VPN to crash on startup

### ISSUE THREAD

**Issue by zun1uwu** [AdvDebug/NoMoreCookies#8]
I've been using NoMoreCookies because I see that it works really well.
However, while it's installed, Mullvad won't start, which surprises me, since it's a VPN and not related to a browsers (apart from the fact that it runs in a chromium sandbox).

I get the following error message:
`Can't access file: file:///C:\Program Files\Mullvad VPN\resources\app.asar\build\src\index.html`

I see the possibility of other programs sharing the same fate, so I think that it's an issue worth looking into.

**Comment by AdvDebug** [comment]
any chromium-based browser will crash if NoMoreCookies inserted itself into it, so if Mullvad is digitally signed then use the first option and this should fix the problem.

**Comment by AdvDebug** [comment]
i may add something to make the user whitelist specific programs later

**Comment by AdvDebug** [comment]
the bug have been fixed and a new release will be available soon :)

**Comment by zun1uwu** [comment]
Interesting, thanks!

**Comment by AdvDebug** [comment]
i fixed it in [NoMoreCookies 2.0](https://github.com/AdvDebug/NoMoreCookies/releases/tag/NoMoreCookies_2.0) Release with the "MiniNoMoreCookies" Mode, sorry for the delay but i had stuff to do.

**Comment by uncaney** [comment]
it continue to crash in the lasted version of mullvad, and also generate BSOD "critical process died" is there any fixing in that ? i'm trying to deploy that company wide but from my testing there are a lot of instability (even on brand new laptop).

**Comment by zun1uwu** [comment]
> it continue to crash in the lasted version of mullvad, and also generate BSOD "critical process died" is there any fixing in that ? i'm trying to deploy that company wide but from my testing there are a lot of instability (even on brand new laptop).

please do not deploy this software in a corporate environment, it's unfinished and, as far as I know, unmaintained. instead train your employees not to run shady programs
