### ISSUE TITLE
Tor and Mullvad browser stopped working

### ISSUE THREAD

**Issue by BoredNerd** [AdvDebug/NoMoreCookies#9]
After I installed NoMoreCookies, apparently Tor and Mullvad browser has stopped working, they only just show a blank grey page, that's it.
So I decided to uninstall NoMoreCookies and it works perfectly. 
Not sure why NoMoreCookies blocks Mullvad and Tor browser.

**Comment by AdvDebug** [comment]
it doesn't block them but NMC have issues with applications that have sandboxing, i will try to fix that issue as fast as possible.

**Comment by AdvDebug** [comment]
the bug have been fixed and a new release will be available soon :)

**Comment by AdvDebug** [comment]
Fixed in [NMC 1.9](https://github.com/AdvDebug/NoMoreCookies/releases/tag/NoMoreCookies_1.9)
